version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
#  java:
#    image: javatesti:latest
#    ports:
#      - "8000:8000"
#    depends_on:
#      - redis
  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=local:redis:6379
      ports:
        - "8081:8081"
volumes:
  redisVolume:
    
